### ISSUE TITLE
a few fixes

### ISSUE THREAD

**Issue by ybrandvain** [JennaHulke/Parasite.Distribution#1]
This code does not work as is 

The following changes are required to get it working

obs.data <- read.csv("test.csv")
source("function.kin.distribution.R") #required to run the kinRelations function
#...
sim.data <- data.frame(matrix(data= NA, nrow= nrow(obs.data), ncol = 4)) # so that host ID is not converted to a character on the first run

**Comment by JennaHulke** [comment]
Thank you, the code has been updated.
